# https://github.com/sphinx-notes/pages/blob/v3/action.yml
# https://help.github.com/en/articles/metadata-syntax-for-github-actions
---
name: drain-swamp-action
description: >-
  Before build pass in drain-swamp build backend plugin parameters
author: >-
  Dave Faulkmore

# https://feathericons.com/
branding:
  color: 'green'
  icon: 'rewind'

inputs:
  plugin_parameters:
    description: >-
      config settings key/value pairs mapping
    required: true
  toml_file_name:
    required: false
    default: 'setuptools-build.toml'
  fetch_tags:
    description: >-
      Fetch git tags
    required: false
    default: false
  checkout:
    description: >-
      Whether to automatically checkout the repository, if false, user need to do it byself
    required: false
    default: true
  python_version:
    description: >-
      Version of Python
    required: false
    default: '3.10'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      if: ${{ inputs.checkout == 'true' && inputs.fetch_tags == 'true' }}
      with:
        fetch-depth: 0
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      if: ${{ inputs.checkout == 'true' && inputs.fetch_tags == 'false' }}

    - name: Setup python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: ${{ inputs.python_version }}
        allow-prereleases: true
        # cache: pip
        # cache-dependency-path: |
        #   requirements.txt

    # Writes to GITHUB_ENV file. In other steps env.TO_TOML and env.MAIN_SH will be available
    # when evaluating boolean,  as opposed to test, this is safer and intuitive
    - name: Set paths
      shell: bash
      run: |
        set -xe
        path_dir=$(git config safe.directory)
        is_not_win=${{ ! startsWith(matrix.os, 'windows') }}
        case $is_not_win in
          (true)    python ${{ github.action_path }}/gh_joinpath.py --name="TO_TOML" "src" "to_toml.py"
                    ;;
          (false)   python '${{ github.action_path }}\gh_joinpath.py' --name="TO_TOML" "src" "to_toml.py"
                    ;;
          *)        echo "Not a boolean"
                    ;;
        esac

    - name: Set script executable
      shell: bash
      run: |
        set -xe
        is_not_win=${{ ! startsWith(matrix.os, 'windows') }}
        # git update-index --chmod=+x '${{ env.TO_TOML }}'
        case $is_not_win in
          (true)    chmod +x ${{ env.TO_TOML }}
                    ;;
          (false)   ;;
          *)        echo "Not a boolean"
                    ;;
        esac

    - name: Prepare temp folder
      shell: bash
      run: |
        set -xe
        echo -e 'temp folder: ${{ runner.temp }} This path is available in environment variable, DS_CONFIG_SETTINGS'
        mkdir -p ${{ runner.temp }} ||:

    - id: outcome
      name: Prepare build backend plugin parameters
      env:
        # See https://github.com/actions/runner/issues/665
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#example-usage-of-the-runner-context
        INPUT_PLUGIN_PARAMETERS: ${{ inputs.plugin_parameters }}
      shell: bash
      run: |
        is_not_win=${{ ! startsWith(matrix.os, 'windows') }}
        case $is_not_win in
          (true)    path_f=${{ runner.temp }}/${{ inputs.toml_file_name }}
                    python '${{ env.TO_TOML }}' $path_f
                    ;;
          (false)   path_f='${{ runner.temp }}\\${{ inputs.toml_file_name }}'
                    python '${{ env.TO_TOML }}' $path_f
                    ;;
          *)        echo "Not a boolean"
                    ;;
        esac

    - name: Show output
      shell: bash
      run: |
        set -xe
        echo 'DS_CONFIG_SETTINGS contains path: ${{ env.DS_CONFIG_SETTINGS }}'
        cat '${{ env.DS_CONFIG_SETTINGS }}'

    # https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs
    # https://github.com/actions/upload-artifact#not-uploading-to-the-same-artifact
    - name: upload artifact
      uses: actions/upload-artifact@v4.4.0
      with:
          name: config-settings-${{ matrix.os }}-${{ inputs.python_version }}
          path: ${{ env.DS_CONFIG_SETTINGS }}
          retention-days: 1
          if-no-files-found: error

...
