# https://github.com/sphinx-notes/pages/blob/v3/action.yml
# https://help.github.com/en/articles/metadata-syntax-for-github-actions
---
name: drain-swamp-action
description: >-
  Before build pass in drain-swamp build backend plugin parameters
author: >-
  Dave Faulkmore

# https://feathericons.com/
branding:
  color: 'green'
  icon: 'rewind'

inputs:
  plugin_parameters:
    description: >-
      config settings key/value pairs mapping
    required: true
  toml_file_name:
    required: false
    default: 'setuptools-build.toml'
  cache:
    description: >-
      Enable checkout cache
    required: false
    default: false
  checkout:
    description: >-
      Whether to automatically checkout the repository, if false, user need to do it byself
    required: false
    default: true
  python_version:
    description: >-
      Version of Python
    required: false
    default: '3.10'

outputs:
  ds_config_settings:
    description: >-
      environment variable containing path to config_settings toml file
    value: ${{ steps.outcome.outputs.ds_config_settings }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      if: ${{ inputs.checkout == 'true' && inputs.cache == 'true' }}
      with:
        fetch-depth: 0
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      if: ${{ inputs.checkout == 'true' && inputs.cache == 'false' }}

    - name: Set script executable -- MacOS or Linux
      if: ${{ ! startsWith(matrix.os, 'windows') }}
      shell: bash
      env:
        PYTHONPATH: ${{ github.action_path }}/src
      run: |
        chmod +x ${{ github.action_path }}/main.sh
        chmod +x ${{ env.PYTHONPATH }}/to_toml.py

    - name: Set script executable -- Windows
      if: startsWith(matrix.os, 'windows')
      shell: bash
      env:
        PYTHONPATH: ${{ github.action_path }}/src
      run: |
        git update-index --chmod=+x ${{ github.action_path }}/main.sh
        git update-index --chmod=+x ${{ env.PYTHONPATH }}/to_toml.py

    - name: Prepare temp folder
      shell: bash
      run: |
        echo -e 'temp folder: ${{ runner.temp }} This path is available in environment variable, DS_CONFIG_SETTINGS'
        mkdir -p ${{ runner.temp }}/ ||:

    - name: Setup python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      if: ${{ inputs.cache == 'true' }}
      with:
        python-version: ${{ inputs.python_version }}
        # cache: 'pip'
    - name: Setup python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      if: ${{ inputs.cache == 'false' }}
      with:
        python-version: ${{ inputs.python_version }}

    - id: outcome
      name: >-
        Prepare build backend plugin parameters
      env:
        # See https://github.com/actions/runner/issues/665
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#example-usage-of-the-runner-context
        PYTHONPATH: ${{ github.action_path }}/src
        DS_CONFIG_SETTINGS: ${{ runner.temp }}/${{ inputs.toml_file_name }}
        INPUT_PLUGIN_PARAMETERS: ${{ inputs.plugin_parameters }}
      shell: bash
      run: ${{ github.action_path }}/main.sh

...
